# This is a basic workflow to help you get started with Actions

name: NuGet Package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .Net Core @ Latest
        uses: actions/setup-dotnet@v1
        
      - name: Install dependencies
        run: |
          cd Plugin.XamarinForms.Converters
          dotnet restore
          
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      
      - name: Generate NuGet package
        run: |
          dotnet pack -c Release -o out  
        
      - name: Add My GPR to sources
        shell: pwsh
        env:  
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: dotnet nuget add source https://nuget.pkg.github.com/saimel/index.json -n "MyGithub" -u $env:PUBLISH_USER -p $env:PUBLISH_TOKEN
      
      - name: Push generated package to Github registry
        run: otnet nuget push ./Plugin.XamarinForms.Converters/out/*.nupkg --source "MyGithub" --skip-duplicate --no-symbols true

